server:
  port: 9009

spring:
  application:
    name: client

eureka:
  instance:
    hostname: localhost
    port: 9001
  client:
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


